### ISSUE TITLE
Cycle counter datasets

### ISSUE THREAD

**Issue by Robinlovelace** [bicischools/bicischools#7]
Would be great to see this visualised, building on our previous paper are there more count points @temospena ?

https://doi.org/10.5194/isprs-archives-XLVIII-4-W1-2022-279-2022

**Comment by temospena** [comment]
Er have the same 67 locations. I'll add the latest data, highlighting the autonomous kids on bikes, right away.

**Comment by temospena** [comment]
sorry about the file name typo 🦆
